"""add data_attributions table

Revision ID: 122d836226d7
Revises: a9b893d4f086
Create Date: 2026-04-13 23:20:52.854830

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '122d836226d7'
down_revision: Union[str, Sequence[str], None] = 'a9b893d4f086'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('data_attributions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('convo_id', sa.Integer(), nullable=False),
    sa.Column('checkpoint_id', sa.String(length=255), nullable=False),
    sa.Column('benchmark', sa.String(length=50), nullable=False),
    sa.Column('method', sa.String(length=50), nullable=False),
    sa.Column('influence_score', sa.Float(), nullable=False),
    sa.Column('z_score', sa.Float(), nullable=True),
    sa.Column('rank', sa.Integer(), nullable=True),
    sa.Column('extra_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('computed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['convo_id'], ['convos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('convo_id', 'checkpoint_id', 'benchmark', 'method', name='uq_attribution_convo_checkpoint_benchmark_method')
    )
    op.create_index(op.f('ix_data_attributions_benchmark'), 'data_attributions', ['benchmark'], unique=False)
    op.create_index(op.f('ix_data_attributions_checkpoint_id'), 'data_attributions', ['checkpoint_id'], unique=False)
    op.create_index(op.f('ix_data_attributions_convo_id'), 'data_attributions', ['convo_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_data_attributions_convo_id'), table_name='data_attributions')
    op.drop_index(op.f('ix_data_attributions_checkpoint_id'), table_name='data_attributions')
    op.drop_index(op.f('ix_data_attributions_benchmark'), table_name='data_attributions')
    op.drop_table('data_attributions')
    # ### end Alembic commands ###
