"""create models

Revision ID: 2fcc394eb798
Revises: 8476b2303fca
Create Date: 2026-02-05 16:48:48.031528

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2fcc394eb798'
down_revision: Union[str, Sequence[str], None] = '8476b2303fca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('models', sa.Column('display_name', sa.String(), nullable=False))
    op.add_column('models', sa.Column('model_type', sa.String(), server_default='vlm', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('models', 'model_type')
    op.drop_column('models', 'display_name')
    # ### end Alembic commands ###
