"""create tasks

Revision ID: 44a797a2eae2
Revises: 2fcc394eb798
Create Date: 2026-02-05 16:54:02.351885

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '44a797a2eae2'
down_revision: Union[str, Sequence[str], None] = '2fcc394eb798'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tasks', 'num_examples',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tasks', 'num_examples',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
