"""create images table

Revision ID: 82b6a69f21d9
Revises: 3edc2dd93a82
Create Date: 2026-01-28 22:23:01.125961

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '82b6a69f21d9'
down_revision: Union[str, Sequence[str], None] = '3edc2dd93a82'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('phash', sa.String(length=16), nullable=False),
    sa.Column('image_url', sa.VARCHAR(), nullable=False),
    sa.Column('image_path', sa.VARCHAR(), nullable=False),
    sa.Column('content_length', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('image_path')
    )
    op.create_index(op.f('ix_images_content_length'), 'images', ['content_length'], unique=False)
    op.create_index(op.f('ix_images_image_url'), 'images', ['image_url'], unique=False)
    op.create_index(op.f('ix_images_phash'), 'images', ['phash'], unique=False)
    op.create_index(op.f('ix_images_sha256'), 'images', ['sha256'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_images_sha256'), table_name='images')
    op.drop_index(op.f('ix_images_phash'), table_name='images')
    op.drop_index(op.f('ix_images_image_url'), table_name='images')
    op.drop_index(op.f('ix_images_content_length'), table_name='images')
    op.drop_table('images')
    # ### end Alembic commands ###
