"""create tasks

Revision ID: 8476b2303fca
Revises: 46de38062691
Create Date: 2026-02-05 16:36:36.324696

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8476b2303fca'
down_revision: Union[str, Sequence[str], None] = '46de38062691'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('display_name', sa.String(), nullable=False))
    op.add_column('tasks', sa.Column('primary_metric_suffix', sa.String(), nullable=False))
    op.add_column('tasks', sa.Column('num_examples', sa.Integer(), nullable=False))
    op.add_column('tasks', sa.Column('paper_url', sa.String(), nullable=False))
    op.add_column('tasks', sa.Column('dataset_url', sa.String(), nullable=False))
    op.add_column('tasks', sa.Column('dataset_version', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'dataset_version')
    op.drop_column('tasks', 'dataset_url')
    op.drop_column('tasks', 'paper_url')
    op.drop_column('tasks', 'num_examples')
    op.drop_column('tasks', 'primary_metric_suffix')
    op.drop_column('tasks', 'display_name')
    # ### end Alembic commands ###
