"""create users

Revision ID: 86b3d09c244e
Revises: 523aefa552fb
Create Date: 2026-02-01 18:40:38.562785

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '86b3d09c244e'
down_revision: Union[str, Sequence[str], None] = '523aefa552fb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # 1) add column as nullable first
    op.add_column("users", sa.Column("password_hash", sa.String(), nullable=True))

    # 2) backfill existing users with a "disabled" placeholder
    # Use a value that can NEVER match a real bcrypt hash so login always fails
    op.execute("UPDATE users SET password_hash = '!unset!' WHERE password_hash IS NULL")

    # 3) enforce not null
    op.alter_column("users", "password_hash", nullable=False)

    op.add_column('users', sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False))
    op.add_column('users', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'created_at')
    op.drop_column('users', 'is_active')
    op.drop_column('users', 'password_hash')
    # ### end Alembic commands ###
