"""Add convo_feedback and convo_comments tables

Revision ID: 8ed00057ee4b
Revises: 3461f617a6f3
Create Date: 2026-10-06 20:12:44.496903

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8ed00057ee4b'
down_revision: Union[str, Sequence[str], None] = '3461f617a6f3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('convo_comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('convo_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('turn_index', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('experiment_bucket', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['convo_id'], ['convos.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_convo_comments_convo_id'), 'convo_comments', ['convo_id'], unique=False)
    op.create_index(op.f('ix_convo_comments_experiment_bucket'), 'convo_comments', ['experiment_bucket'], unique=False)
    op.create_index(op.f('ix_convo_comments_user_id'), 'convo_comments', ['user_id'], unique=False)
    op.create_table('convo_feedback',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('convo_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('turn_index', sa.Integer(), nullable=False),
    sa.Column('thumbs', sa.String(length=10), nullable=True),
    sa.Column('edit_original', sa.Text(), nullable=True),
    sa.Column('edit_revised', sa.Text(), nullable=True),
    sa.Column('experiment_bucket', sa.String(length=50), nullable=True),
    sa.Column('available_actions', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['convo_id'], ['convos.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_convo_feedback_convo_id'), 'convo_feedback', ['convo_id'], unique=False)
    op.create_index(op.f('ix_convo_feedback_experiment_bucket'), 'convo_feedback', ['experiment_bucket'], unique=False)
    op.create_index(op.f('ix_convo_feedback_user_id'), 'convo_feedback', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_convo_feedback_user_id'), table_name='convo_feedback')
    op.drop_index(op.f('ix_convo_feedback_experiment_bucket'), table_name='convo_feedback')
    op.drop_index(op.f('ix_convo_feedback_convo_id'), table_name='convo_feedback')
    op.drop_table('convo_feedback')
    op.drop_index(op.f('ix_convo_comments_user_id'), table_name='convo_comments')
    op.drop_index(op.f('ix_convo_comments_experiment_bucket'), table_name='convo_comments')
    op.drop_index(op.f('ix_convo_comments_convo_id'), table_name='convo_comments')
    op.drop_table('convo_comments')
    # ### end Alembic commands ###
