"""create tasks models

Revision ID: 9c5d2df0ad4c
Revises: 44a797a2eae2
Create Date: 2026-02-05 16:57:06.252705

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9c5d2df0ad4c'
down_revision: Union[str, Sequence[str], None] = '44a797a2eae2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('models', 'display_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('models', 'default_args',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True)
    op.alter_column('tasks', 'paper_url',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('tasks', 'dataset_url',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('tasks', 'dataset_version',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tasks', 'dataset_version',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('tasks', 'dataset_url',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('tasks', 'paper_url',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('models', 'default_args',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False)
    op.alter_column('models', 'display_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
