"""add created_at to convos

Revision ID: aca134536d08
Revises: 82b6a69f21d9
Create Date: 2026-01-28 22:37:35.644681

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aca134536d08'
down_revision: Union[str, Sequence[str], None] = '82b6a69f21d9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('convos', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.create_index(op.f('ix_convos_created_at'), 'convos', ['created_at'], unique=False)
    op.create_index(op.f('ix_convos_user_id'), 'convos', ['user_id'], unique=False)
    op.create_foreign_key(None, 'convos', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'convos', type_='foreignkey')
    op.drop_index(op.f('ix_convos_user_id'), table_name='convos')
    op.drop_index(op.f('ix_convos_created_at'), table_name='convos')
    op.drop_column('convos', 'created_at')
    # ### end Alembic commands ###
