"""create models

Revision ID: db684f3c17b7
Revises: 86b3d09c244e
Create Date: 2026-02-05 00:04:58.185367

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'db684f3c17b7'
down_revision: Union[str, Sequence[str], None] = '86b3d09c244e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('models',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('vlmeval_model', sa.String(), nullable=False),
    sa.Column('default_args', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('vlmeval_data', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('primary_metric', sa.String(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tasks_created_at'), 'tasks', ['created_at'], unique=False)
    op.create_index(op.f('ix_tasks_name'), 'tasks', ['name'], unique=True)
    op.create_index(op.f('ix_tasks_user_id'), 'tasks', ['user_id'], unique=False)
    op.create_index(op.f('ix_tasks_vlmeval_data'), 'tasks', ['vlmeval_data'], unique=False)
    op.create_table('eval_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('model_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('QUEUED', 'RUNNING', 'COMPLETE', 'FAILED', name='evalstatus'), nullable=False),
    sa.Column('metrics', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('artifacts_dir', sa.String(), nullable=False),
    sa.Column('command', sa.String(), nullable=False),
    sa.Column('git_commit', sa.String(), nullable=False),
    sa.Column('error', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['model_id'], ['models.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_eval_runs_created_at'), 'eval_runs', ['created_at'], unique=False)
    op.create_index(op.f('ix_eval_runs_model_id'), 'eval_runs', ['model_id'], unique=False)
    op.create_index(op.f('ix_eval_runs_task_id'), 'eval_runs', ['task_id'], unique=False)
    op.add_column('convos', sa.Column('started_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('convos', sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_convos_finished_at'), 'convos', ['finished_at'], unique=False)
    op.create_index(op.f('ix_convos_started_at'), 'convos', ['started_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_convos_started_at'), table_name='convos')
    op.drop_index(op.f('ix_convos_finished_at'), table_name='convos')
    op.drop_column('convos', 'finished_at')
    op.drop_column('convos', 'started_at')
    op.drop_index(op.f('ix_eval_runs_task_id'), table_name='eval_runs')
    op.drop_index(op.f('ix_eval_runs_model_id'), table_name='eval_runs')
    op.drop_index(op.f('ix_eval_runs_created_at'), table_name='eval_runs')
    op.drop_table('eval_runs')
    op.drop_index(op.f('ix_tasks_vlmeval_data'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_user_id'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_name'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_created_at'), table_name='tasks')
    op.drop_table('tasks')
    op.drop_table('models')
    # ### end Alembic commands ###
