"""create convos table

Revision ID: e81a0ec6988a
Revises: 679b8f77017a
Create Date: 2026-01-27 21:32:50.600445

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e81a0ec6988a'
down_revision: Union[str, Sequence[str], None] = '679b8f77017a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('convos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('image', sa.String(), nullable=False),
    sa.Column('conversations', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('model_name', sa.String(), nullable=False),
    sa.Column('model_type', sa.String(), nullable=False),
    sa.Column('task', sa.String(), server_default='open', nullable=False),
    sa.Column('feedback', sa.Text(), nullable=False),
    sa.Column('monetized', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('enabled', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('convos')
    # ### end Alembic commands ###
